### ISSUE TITLE
Windows Server 2012 동작 않음

### ISSUE THREAD

**Issue by haje01** [haje01/conmon#1]
Windows Server 2012에서 동작 않음. psutil 권한 문제인 듯

https://github.com/giampaolo/psutil/issues/599

**Comment by haje01** [comment]
PyInstaller 적용하여 해결

**Comment by whpark70** [comment]
PyInstaller로 어떻게 해결하셨는지 궁금합니다.
administrator 권한으로 해도 psutil.disk_io_counters()는 아무런 값도 display되지 않습니다.

**Comment by haje01** [comment]
좀 가물가물한데.. 제가 psutil을 이용한 코드를 참고하시면 도움이 되실지도 모르겠습니다..

https://github.com/haje01/conmon <https://github.com/haje01/conmon>
